### PR TITLE
unknown-function-variation test case

### PR DESCRIPTION
**Pull request by bbigras**
That was from my configuration.nix file. Not sure how to call the test case.

Output:

```nix
Unknown function variation { config, pkgs, ... }:
```

### CODE REVIEW

**Comment by justinwoo** [comment]
Oh, it's a rest argument or whatever it's called in nixlang. Woudl be good to see the output of this to see what is up

**Comment by bbigras** [comment]
My first message in this issue has the output. Unless you mean from those output files when we run `npm test`.

**Comment by justinwoo** [comment]
right, with the output. it would also be good to make this a valid expression rather than a partial one

**Comment by bbigras** [comment]
I just pushed a new commit which I think is a valid expression.

Here's the relevant part of output.nix:

```nix
(expression (function (formals (formal (identifier)) (formal (identifier))) (ellipses) (attrset (bind (attrpath (identifier) (identifier)) (string)))))
Unknown function variation { config, pkgs, ... }:

{
  system.stateVersion = "19.09";
}
```

**Comment by justinwoo** [comment]
Cool, thanks

**Comment by justinwoo** [comment]
This might be fixed by updating tree-sitter-nix https://github.com/cstrahan/tree-sitter-nix/commit/c885d29d567d5d99c0774da7ee20a575a0b733f4

**Pull request merged**
